spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  redis:
    timeout: 20s
    host: localhost
    port: 6379
    database: 3
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 20s
        min-idle: 5
        shutdown-timeout: 5000ms